[runner]
fastReruns = true

[server]
runOnSave = true
headless = true
enableStaticServing = true

[theme]
base="light"
primaryColor="#79BDF8"
backgroundColor="#B5DCFF"
secondaryBackgroundColor="#DCEEFF"
textColor="#31333F"
font="sans serif"